language: node_js
notifications:
  email:
    recipients:
      - evgeniy.ryabchenko.175@gmail.com
    on_success: never
    on_failure: always
node_js:
  - "node"
  - "6"
before_script:
  - npm install